spring:
  application:
    name: showCode

#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
